# Generated by Django 6.0.1 on 2026-02-01 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_aluno_data_ingresso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DurationField(verbose_name='Quantidade de horas')),
                ('data_registro', models.DateField(verbose_name='Data de registro')),
                ('oficio_informacao', models.CharField(max_length=200, verbose_name='Ofício de informação')),
                ('oficio_documento', models.FileField(upload_to='oficios/', verbose_name='Ofício de documento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='academico.aluno', verbose_name='Aluno')),
                ('responsavel_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_registro', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo registro')),
            ],
            options={
                'verbose_name': 'Horas',
                'verbose_name_plural': 'Horas',
                'ordering': ['data_registro'],
            },
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(auto_created=True, unique=True, verbose_name='Número')),
                ('data', models.DateField(verbose_name='Data')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamentos', to='academico.aluno', verbose_name='Aluno')),
                ('responsavel_emissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamentos_emissao', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela emissão')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.secretaria', verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Encaminhamento',
                'verbose_name_plural': 'Encaminhamentos',
                'ordering': ['numero'],
            },
        ),
    ]
