# Generated by Django 6.0.1 on 2026-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horas',
            name='oficio_documento',
            field=models.FileField(blank=True, null=True, upload_to='oficios/', verbose_name='Ofício de documento'),
        ),
    ]
