# Generated by Django 6.0.1 on 2026-02-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_aluno_data_ingresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=10, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
