# Generated by Django 6.0.1 on 2026-01-29 20:11

import apps.usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.usuarios.models.CustomUserManager()),
            ],
        ),
    ]
